# Values for gitlab/gitlab chart on GKE
global:
  edition: ce
  hosts:
    domain: xip.io
    https: true
    gitlab: {}
    externalIP: 192.168.56.110 #Replace by your Nginx Ingress ExternalIP
    ssh: ~
    gitlab:
      name: gitlab.xip.io 
      https: true
    registry:
      name: gitlab-registry.xip.io
      https: true
    minio:
      name: gitlab-minio.xip.io
      https: true
  minio:
    enabled: true
  ## doc/charts/globals.md#configure-ingress-settings
  ingress:
    configureCertmanager: false
    class: "nginx"
    enabled: true
    tls:
      enabled: true
certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: true
redis:
  install: true
postgresql:
  install: true
gitlab-runner:
  install: true
registry:
  enable: true