
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.synced_folder "./confs", "/home/vagrant/.confs"

  config.vm.define "tde-camaS" do |master|
    master.vm.hostname = "tde-camaS"
    master.vm.network "private_network", bridge: "eth1", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb1.customize ["modifyvm", :id, "--name", "tde-camaS"]
      vb1.memory = "1024"
      vb1.cpus = "1"
    end
    master.vm.provision :shell, :path => "scripts/master.sh", env: {"KUBECONFIG" => "/home/vagrant/.kube/config"}

end
