
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.synced_folder "./confs", "/home/vagrant/.confs"
  config.vm.network "forwarded_port", guest: 8888, host: 8888

  config.vm.define "tde-camaS" do |master|
    master.vm.hostname = "tde-camaS"
    # master.vm.network "private_network", bridge: "eth1", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "tde-camaS"]
      vb.memory = "2048"
      vb.cpus = "2"
    end
    master.vm.provision :shell, :path => "scripts/master.sh", env: {"KUBECONFIG" => "/home/vagrant/.kube/config"}
  end
  
end
